### ISSUE TITLE
Can't Start or reinstall addon after upgrade to 0.4.3

### ISSUE THREAD

**Issue by dikt1338** [da-anda/hass-io-addons#17] opened 2022-04-14 11:17 UTC
After upgrading the Addon to 0.4.3 the addon does not start.
Reinstalling fails with the following error message:

Can't install ghcr.io/da-anda/hass-io-addons-aarch64-addon-knxd:0.4.3: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=0.4.3&fromImage=ghcr.io%2Fda-anda%2Fhass-io-addons-aarch64-addon-knxd&platform=linux%2Farm64: Internal Server Error ("Head "https://ghcr.io/v2/da-anda/hass-io-addons-aarch64-addon-knxd/manifests/0.4.3": denied")

**Comment by dikt1338** [comment] 2022-04-14 11:19
Adding my Home Assistant Info in case this helps:
## System Health

version | core-2022.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 228.5 GB
disk_used | 25.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Dropbox Sync (1.3.0), Node-RED (11.1.1), Mosquitto broker (6.0.1), SSH & Web Terminal (10.1.1), ESPHome (2022.3.1), UniFi Network Application (2.1.0), Studio Code Server (4.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 12
views | 13
mode | storage

</details>

**Comment by da-anda** [comment] 2022-04-14 11:23
hi. Thanks for the report. I know. I just merged a PR that switched the add-on from compiling it directly on the device to using pre-compiled add-ons. But the compilation via github actions seems to fail and thus the image is not available. As a short term "fix", I removed the installation via pre-build image again, but kept the version bump of knx and the add-on.
You might have to tell HomeAssistant/Supervisor to once again check for updates in order for it to load the latest version of the manifest file, and then try to re-install it again. This time it should work again, as it will compile on the device again, just like before.

**Comment by da-anda** [comment] 2022-04-14 11:51
well, even the revert doesn't seem to fix the issue. Sorry, should not have blindly trusted PR #16 and do some more in depth testing. Will revert the entire commit for now, since on local compile I also ran into issue - probably due to the changed base image

**Comment by dikt1338** [comment] 2022-04-14 11:55
Hi. Thanks for the fast response. I will revert to my backup for now

**Comment by da-anda** [comment] 2022-04-14 11:59
I just reverted the version bump until I have more time to debug the issue

**Comment by VadimKraus** [comment] 2022-04-14 12:28
@da-anda hey I tried to reproduce the issue on my side

could you please check your settings at settings -> actions -> https://github.com/da-anda/hass-io-addons/settings/actions 

![image](https://user-images.githubusercontent.com/38394456/163389894-bdcf2c50-3695-4e29-9ab9-fccc2a52b506.png)


If I set this to "Read repository contents permission" I see the same errors in my workflows.

**Comment by da-anda** [comment] 2022-04-14 12:36
yeah, it's set to "read" since it doesn't really need to write, does it? But I can change to RW. But during my local compile test, I also noticed that the `2-init-config` script now fails because it can't find `bashio`. Currently trying to debug it, but compiling on my RPI4 takes some time after each iteration. Probably should SSH into the container, but my time is quite limited atm

**Comment by da-anda** [comment] 2022-04-14 13:41
@VadimKraus ok, the `bashio` issue is resolved - GIT auto-converted the line endings to CRLF, which bash ofc doesn't like

**Comment by VadimKraus** [comment] 2022-04-14 14:34
yeah just tested it again, could not find any issue with any of the build containers. 

I guess write access is required, since the images need to be pushed into your packages.

**Comment by da-anda** [comment] 2022-04-14 16:05
@VadimKraus thanks for your PR and your help. Issues are sorted now, packages public and installation seems to work fine. Thanks.

**Closed by da-anda** 2022-04-14 16:05 UTC
